apiVersion: v2
name: pagopa-afm-marketplace
description: Microservice that handles marketplace for pagoPA Advanced Fees Management
type: application
version: 0.81.0
appVersion: 0.21.0
dependencies:
  - name: microservice-chart
    version: 2.4.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
