apiVersion: v2
name: pagopa-afm-marketplace
description: Microservice that handles marketplace for pagoPA Advanced Fees Management
type: application
version: 0.54.0
appVersion: 0.15.7-2-VAS-1025-fix-validity-date-from-filter
dependencies:
  - name: microservice-chart
    version: 2.4.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
