apiVersion: v2
name: pagopa-afm-marketplace
description: Microservice that handles marketplace for pagoPA Advanced Fees Management
type: application
version: 0.3.3-2
appVersion: 0.3.3-2
dependencies:
  - name: microservice-chart
    version: 1.21.0
    repository: "file:///Users/francesco/Development/PagoPA/aks-microservice-chart-blueprint/charts/microservice-chart"
